[package]
name = "scenelib"
version = "0.1.0"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"

[dependencies]
svg = "0.8.0"
rstar = "0.7.1"
nalgebra = "0.20"
wasm-bindgen = "0.2.62"
js-sys = "0.3.39"

[lib]
crate-type = ["cdylib", "rlib"]